import type { Agent, AgentId } from "./types";

export const AGENTS: Agent[] = [
  {
    id: "fundamental",
    code: "FND",
    abbrev: "FA",
    title: "Fundamental Analyst",
    name: "M. Chen",
    seat: "04-A",
    mandate: "Filings, NTM, cash, dilution. No tape.",
  },
  {
    id: "news",
    code: "NWS",
    abbrev: "NA",
    title: "News Analyst",
    name: "E. Walsh",
    seat: "04-B",
    mandate: "Headlines, filings, event risk. 5-day horizon.",
  },
  {
    id: "sentiment",
    code: "SEN",
    abbrev: "SA",
    title: "Sentiment Analyst",
    name: "A. Okonkwo",
    seat: "04-C",
    mandate: "Skew, flow, polarity. 10-day horizon.",
  },
  {
    id: "technical",
    code: "TEC",
    abbrev: "TA",
    title: "Technical Analyst",
    name: "L. Varga",
    seat: "04-D",
    mandate: "Levels, RSI, MACD, volume. Stops only.",
  },
  {
    id: "bull",
    code: "BUL",
    abbrev: "BR",
    title: "Bull Researcher",
    name: "R. Patel",
    seat: "04-E",
    mandate: "Long case. Must answer the bear with the same facts.",
  },
  {
    id: "bear",
    code: "BER",
    abbrev: "BE",
    title: "Bear Researcher",
    name: "S. Novak",
    seat: "04-F",
    mandate: "Short case. Must answer the bull with the same facts.",
  },
  {
    id: "trader",
    code: "TRD",
    abbrev: "T",
    title: "Trader",
    name: "J. Hale",
    seat: "04-G",
    mandate: "Size and timing. One proposal per name.",
  },
  {
    id: "aggressive",
    code: "AGR",
    abbrev: "RA",
    title: "Aggressive Risk",
    name: "D. Okada",
    seat: "04-H",
    mandate: "Push size. Accept factor risk if the idea is clean.",
  },
  {
    id: "conservative",
    code: "CSV",
    abbrev: "RC",
    title: "Conservative Risk",
    name: "H. Berg",
    seat: "04-I",
    mandate: "Cut size. Punish IV, drawdown, new sleeves.",
  },
  {
    id: "neutral",
    code: "NEU",
    abbrev: "RN",
    title: "Neutral Risk",
    name: "P. Iyer",
    seat: "04-J",
    mandate: "Median the committee. No heroics.",
  },
  {
    id: "risk",
    code: "RSK",
    abbrev: "RM",
    title: "Risk Judge",
    name: "K. Sato",
    seat: "04-K",
    mandate: "Apply hard limits. Veto, trim, last word.",
  },
];

export const AGENT_BY_ID: Record<AgentId, Agent> = Object.fromEntries(
  AGENTS.map((agent) => [agent.id, agent]),
) as Record<AgentId, Agent>;
