import type { Ticket } from "./types";

export const SEED_BLOTTER: Ticket[] = [
  {
    id: "MSFT-2026-09-18",
    ticker: "MSFT",
    side: "BUY",
    proposedSide: "BUY",
    proposedSizePct: 2,
    sizePct: 2,
    shares: 47,
    proposedShares: 47,
    mark: 424.1,
    stop: 409,
    thesis: "Azure intact. 2% add on the 50d hold.",
    riskNote: "Approved 2.0%.",
    vetoed: false,
    trimmed: false,
    status: "filled",
    ts: "2026-09-18T19:41:00.000Z",
  },
  {
    id: "JPM-2026-09-17",
    ticker: "JPM",
    side: "BUY",
    proposedSide: "BUY",
    proposedSizePct: 4,
    sizePct: 4,
    shares: 200,
    proposedShares: 200,
    mark: 198.5,
    stop: 190,
    thesis: "NII stable. Opened the sleeve @ 198.50.",
    riskNote: "Approved 4.0%.",
    vetoed: false,
    trimmed: false,
    status: "filled",
    ts: "2026-09-17T18:12:00.000Z",
  },
  {
    id: "XOM-2026-09-16",
    ticker: "XOM",
    side: "HOLD",
    proposedSide: "BUY",
    proposedSizePct: 5,
    sizePct: 0,
    shares: 0,
    proposedShares: 426,
    mark: 117.4,
    stop: null,
    thesis: "Energy sleeve rejected. Wait for 112.",
    riskNote: "Veto. No sector open into WTI chop.",
    vetoed: true,
    trimmed: false,
    status: "vetoed",
    ts: "2026-09-16T15:04:00.000Z",
  },
];
